FROM python:3.7

# COPY requirements.txt .

# ADD . /home/

RUN apt-get update && apt-get install -y \
    libdbus-1-dev \
    libgirepository1.0-dev \
    libpcre3 \
    libpcre3-dev
RUN apt-get update && apt-get install -y \
    tmux \
    vim
RUN python -m pip install --upgrade pip setuptools wheel
# RUN pip install dbus-python PyGObject
# RUN pip install -r requirements.txt
RUN pip install uwsgi -I --no-cache-dir
# RUN python manage.py makemigrations

# CMD ["uwsgi", "-i", "/home/api_server/kakao_chatbot/uwsgi.ini"]