# Generated by Django 3.2.25 on 2024-06-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('registerId', models.CharField(max_length=20)),
                ('registerDatete', models.DateField()),
            ],
        ),
    ]
