# Generated by Django 3.2.25 on 2024-07-01 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='registerDatete',
            field=models.TimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
