# Generated by Django 3.2.25 on 2024-07-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20240701_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='registerDatete',
        ),
        migrations.AddField(
            model_name='board',
            name='registerDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
