# Generated by Django 3.2.25 on 2024-07-01 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20240701_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='content',
            new_name='BOARD_CONTENT',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='id',
            new_name='BOARD_ID',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='title',
            new_name='BOARD_TITLE',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='registerDate',
            new_name='REGISTER_DATE',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='registerId',
            new_name='REGISTER_ID',
        ),
    ]
