# Generated by Django 3.2.25 on 2024-07-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20240701_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='BOARD_CONTENT',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='BOARD_ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='REGISTER_DATE',
            new_name='registerDate',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='REGISTER_ID',
            new_name='registerId',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='BOARD_TITLE',
            new_name='title',
        ),
    ]
