# Generated by Django 3.2.25 on 2024-07-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20240701_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='registerId',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
